export const resList = [
    {
        id: 1,
        name: "Amaltaas - Cantt",
        cuisine: "Pakistani",
        avg_rating: 4.9,
        no_of_rating: 15,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/p6tx-listing.jpg?width=400&height=225",
    },
    {
        id: 2,
        name: "BG Rouge - Cantt",
        cuisine: "Burgers",
        avg_rating: 4.9,
        no_of_rating: 34,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/tcdh-listing.jpg?width=400&height=225",
    },
    {
        id: 3,
        name: "Ahmad Dahi Bhallay - Cavalary Ground",
        cuisine: "Pakistani",
        avg_rating: 4.9,
        no_of_rating: 1100,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/rtvr-listing.jpg?width=400&height=225",
    },
    {
        id: 4,
        name: "Awesamosas",
        cuisine: "Pakistani",
        avg_rating: 4.2,
        no_of_rating: 115,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/q1ml-listing.jpg?width=400&height=225",
    },
    {
        id: 5,
        name: "KLAP",
        cuisine: "Fast Food",
        avg_rating: 4.8,
        no_of_rating: 115,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/nhs3-listing.jpg?width=400&height=225",
    },
    {
        id: 6,
        name: "Dumplings Bar",
        cuisine: "Chinese",
        avg_rating: 3.8,
        no_of_rating: 98,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/oqyq-listing.jpg?width=400&height=225",
    },
    {
        id: 7,
        name: "Faisal Zahoor Restaurant",
        cuisine: "Pakistan",
        avg_rating: 4.9,
        no_of_rating: 2500,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/v4qx-listing.jpg?width=400&height=225",
    },
    {
        id: 8,
        name: "Jumbo Gyro - Cavalry",
        cuisine: "Fast Food",
        avg_rating: 4.6,
        no_of_rating: 140,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/m6ph-listing.jpg?width=400&height=225",
    },
    {
        id: 9,
        name: "OPTP - Girja Chowk",
        cuisine: "Fast Food",
        avg_rating: 4.8,
        no_of_rating: 3500,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/x1cm-listing.jpg?width=400&height=225",
    },
    {
        id: 10,
        name: "Third Culture Coffee - Cantt",
        cuisine: "Healthy Food",
        avg_rating: 4.9,
        no_of_rating: 69,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/xqgz-listing.jpg?width=400&height=225",
    },
    {
        id: 11,
        name: "Wock Rock Chinese",
        cuisine: "chinese",
        avg_rating: 4.5,
        no_of_rating: 8,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/dea6-listing.jpg?width=400&height=225",
    },
    {
        id: 12,
        name: "Dera Restaurant - Cavalry Ground",
        cuisine: "Pasta",
        avg_rating: 4.6,
        no_of_rating: 560,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/fgaw-listing.jpg?width=400&height=225",
    },
    {
        id: 13,
        name: "Haagen Dazs - Cavalry Ground",
        cuisine: "Deserts",
        avg_rating: 3.0,
        no_of_rating: 34,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/e50u-listing.jpg?width=400&height=225",
    },
    {
        id: 14,
        name: "CP Five Star - Cavalry",
        cuisine: "Fast Food",
        avg_rating: 4.9,
        no_of_rating: 1200,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/oeme-listing.jpg?width=400&height=225",
    },
    {
        id: 15,
        name: "Double Shot",
        cuisine: "Beverages",
        avg_rating: 4,
        no_of_rating: 190,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/buzs-listing.jpg?width=400&height=225",
    },
    {
        id: 16,
        name: "Qissa Khawani Restaurant",
        cuisine: "Pakistani",
        avg_rating: 4.9,
        no_of_rating: 134,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/tmun-listing.jpg?width=400&height=225",
    },
    {
        id: 17,
        name: "Dally Food",
        cuisine: "Chinese",
        avg_rating: 3.7,
        no_of_rating: 534,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/yvix-listing.jpg?width=400&height=225",
    },
    {
        id: 18,
        name: "Kent Broast",
        cuisine: "Pakistani",
        avg_rating: 4.1,
        no_of_rating: 534,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/eb6b-listing.jpg?width=400&height=225",
    },
    {
        id: 19,
        name: "XO Chinese Chips",
        cuisine: "Chinese",
        avg_rating: 4.8,
        no_of_rating: 134,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/sfvv-listing.jpg?width=400&height=225",
    },
    {
        id: 20,
        name: "Rubi's Kitchen",
        cuisine: "Pakistani",
        avg_rating: 4.9,
        no_of_rating: 19,
        imgSrc: "https://images.deliveryhero.io/image/fd-pk/LH/q68f-listing.jpg?width=400&height=225",
    },
]